services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: 'npm run start:dev'
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules

  posts-database:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
    restart: always
    volumes:
      - posts-database-volume:/var/lib/postgresql/data
volumes:
  posts-database-volume:
