services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: 'npm run start:dev'
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
      - posts-database

  posts-database:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always
    volumes:
      - posts-database-volume:/var/lib/postgresql/data

  nats-serwer:
    image: nats:latest
    expose:
      - "4222"
    ports:
      - '4222:4222'
      - '8222:8222'
    environment:
      - NATS_MAX_PAYLOAD=4MB
      - NATS_LOG_LEVEL=debug
    command: ["-js", "--http_port", "8222"]


volumes:
  posts-database-volume:
